### PR TITLE
Update create-your-first-plugin.md

### PR DESCRIPTION
**Pull request by action-hong**
In my opinion, it should be "dice", not “die”

### CODE REVIEW

**Comment by marcusolsson** [comment]
AFAIK "die" is used for singular, and "dice" for plural, and the icon only has one die? Could you share some more insights on why it should be "dice"?

**Comment by action-hong** [comment]
I've just learned that that die is the singular form of dice. but I looked it up and it seems that nowadays dice can be used as [both singular and plural](https://www.lexico.com/en/definition/dice):

> Historically, dice is the plural of die, but in modern English dice is sometimes also used in the singular: throw the dice could mean a reference to either one or more than one dice

and [From an article in Mirror](https://www.mirror.co.uk/news/uk-news/people-want-brexit-elitist-politicians-8182888)

> He thought quite the opposite, and so do millions of ordinary Brits. It’s by staying in that we’re rolling **the dice** with our childrens’ future.

Both "die" and "dice" can be used, so there is no need for this modification.

thinks you reply

**Comment by marcusolsson** [comment]
Interesting! Didn't know you could use dice as singular! Thanks for taking the time to help!

**Comment by action-hong** [comment]
@marcusolsson BTW, Your docs is awesome, I would like to translate it into Chinese except for the **API Reference**, it may take a month or two,  I don't know if you agree or not.

I'm sorry I didn't ask for your agreement. here is [a website](https://action-hong.github.io/obsidian-plugin-docs/) with **Getting Started** has been translated roughly. I'll not delete it until you reply.

**Comment by marcusolsson** [comment]
Wow! That's really cool! I don't have that much experience with docs translations, but I'd be happy to make it happen!

**Comment by action-hong** [comment]
me too, I don't have much experience

Since I'm the only translator, here is a simple plan:

1. fork this repository
2. [add the i18n support](https://docusaurus.io/docs/i18n/tutorial)
3. make a commit after translate an article(maybe need proofreading if other translators are involved in the future)
4. make a PR after the translation is complete(or partially translated)

What do you think.

**Comment by marcusolsson** [comment]
Just came back from vacation, and haven't been able to look into this yet. I'll read up on the i18n support and get back to you.

**Comment by action-hong** [comment]
looking forward to your reply

**Pull request closed without merging**
